version: '3.8'

name: 'cep-api'

services:
  db:
    image: postgres:15-alpine
    container_name: app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cep
    ports:
      - '5432:5432'
    volumes:
      - .pg-data:/var/lib/postgresql/data
